version: "3"

services:
    hippotech:
        container_name: hippotech
        build:
            context: .
        ports:
            - 3001:3001
        hostname: hippotech
        environment: 
            APPROVAL_URL: "http://approval:4002"
            BLOG_URL: "http://blog:4003"

    approval:
        container_name: approval
        hostname: approval
        build:
            context: ./approval
        environment: 
            FRAUD_URI: "fraud:4005"
            KAFKA_URI: "kafka:9092"
            KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"

    credit:
        container_name: credit
        hostname: credit
        build:
            context: ./credit        

    mongo:
        image: mongo
        container_name: mongo
        hostname: mongo
        restart: always

    fraud:
        container_name: fraud
        hostname: fraud
        ports:
        - 4004:4004
        build:
            context: ./fraud

    blog:
        container_name: blog
        hostname: blog
        build:
            context: ./blog
        ports:
            - 4003:4003
        environment: 
            MONGO_URL: "mongodb://mongo:27017"
        depends_on: 
            - mongo

    zookeeper:
        image: confluentinc/cp-zookeeper:5.4.4
        hostname: zookeeper
        container_name: zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181
    
    kafka:
        image: confluentinc/cp-kafka:5.4.4
        hostname: kafka
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    hippodb:
        container_name: hippodb
        hostname: hippodb
        image: postgres:14
        environment:
            "POSTGRES_USER": 'hippotech'
            "POSTGRES_PASSWORD": 'hippotech'
            "POSTGRES_DB": 'hippotech'
        